spring:
  application:
    name: deokhugam
  profiles:
    active: local   # 기본값 로컬, ECS에서는 환경변수로 dev로 오버라이드

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{clientIp}] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never